CREATE DATABASE IF NOT EXISTS GOURMET
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

USE GOURMET;

CREATE TABLE USUARIOS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  contraseña VARCHAR(255) NOT NULL,
  direccion VARCHAR(255),
  telefono VARCHAR(20)
);

CREATE TABLE PRODUCTOS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  descripcion TEXT,
  categoria VARCHAR(50),
  precio DECIMAL(10,2) NOT NULL,
  cantidad_inventario INT NOT NULL DEFAULT 0
);

CREATE TABLE CARRITO (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_usuario INT NOT NULL,
  id_producto INT NOT NULL,
  cantidad INT NOT NULL,
  monto_total DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id),
  FOREIGN KEY (id_producto) REFERENCES PRODUCTOS(id)
);
